---
- name: Install AdGuard
  hosts: all
  roles:
    - adguard
  vars:
    adguardhome_user: "adguard"
    adguardhome_group: "adguard"
  become: true
  tags:
    - adguard

- name: Install Docker
  hosts: all
  roles:
    -  geerlingguy.pip
    -  geerlingguy.docker
  vars:
   docker_users:
    - root
   pip_install_packages:
    - name:
        - docker
  become: true
  tags:
    - docker

- name: Install Caddy Webserver
  hosts: all
  roles:
   - nvjacobo.caddy
  vars:
    caddy_package: caddy
    caddy_package_state: present
  become: true
  tags:
    - caddy

- name: Install Plex Server
  hosts: plexserver
  roles:
   - plex
  become: true
  tags:
    - plex

- name: Install Jellyfin Server
  hosts: jellyfinserver
  roles:
   - ansible-jellyfin
  vars:
   jellyfin_name: "jellyfin"
   jellyfin_group: "arcana"
   jellyfin_skip_restart: false
   jellyfin_enable_fail2ban: false
   jellyfin_fail2ban_ports:
    - "80"
    - "443"
   jellyfin_fail2ban_maxretry: "3"
   jellyfin_fail2ban_bantime: "6000"
   jellyfin_fail2ban_findtime: "600"

   jellyfin_cache_dir: "/var/cache/jellyfin"
   jellyfin_log_dir: "/var/log/jellyfin"
   jellyfin_config_dir: "/etc/jellyfin"
   jellyfin_data_dir: "/var/lib/jellyfin"

   jellyfin_ffmpeg_bin: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
   jellyfin_web_bin: "/usr/share/jellyfin/web"
  become: true
  tags:
    - jellyfin