---
- name: Ping Test
  hosts: all
  tasks:
   - name: Pings host
     ansible.builtin.ping:
  tags:
    - ping

- name: Installing Updates & Common Packages
  hosts: all
  roles:
   - common
  become: true
  tags:
    - common

- name: Create User(s)
  hosts: all
  roles:
   - ryandaniels.create_users
  vars_files:
   - ./useradd
  become: true
  tags:
    - createusers

# Make sure to have git install, I didn't do it here in case this needs to be run as a non-root user.
- name: Installing dotfiles
  hosts: all
  roles:
   - geerlingguy.dotfiles
  vars:
   dotfiles_repo: "https://github.com/Terell-Davis/dotfiles.git"
   dotfiles_repo_version: master
   dotfiles_repo_local_destination: "~/dotfiles"
   dotfiles_home: "~"
   dotfiles_files:
    - .aliases
    - .bash_profile
    - .bash_prompt
    - .exports
    - .bashrc
  tags:
    - dotfiles

- name: Setup ufw
  hosts: all
  roles:
   - ufw
  vars:
   ports:
    - 22
  become: true
  tags:
    - ufw

- name: Install goLang
  hosts: all
  roles:
    - geerlingguy.go
  tags:
    - golang
