- name: Testing Connections
  hosts: all
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world

- name: Mount SMB Share
  hosts: all
  become: true
  vars:
    src_uri: "//windows-pc/share"
    smb_username: "example@domain"
    smb_password: "password"
    mountpoint: "/share"
  tasks:
    - name: utility present
      ansible.builtin.package:
        name: cifs-utils
        state: present